"""empty message

Revision ID: 74fb04b101a1
Revises: 
Create Date: 2018-06-16 14:55:20.598249

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '74fb04b101a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_history',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('book_title', sa.String(length=30), nullable=True),
    sa.Column('time_borrowed', sa.DateTime(), nullable=True),
    sa.Column('date_borrowed', sa.DateTime(), nullable=True),
    sa.Column('return_date', sa.DateTime(), nullable=True),
    sa.Column('book_returned', sa.Boolean(), nullable=True),
    sa.Column('user_history', sa.String(), nullable=True),
    sa.Column('book_history', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_history'], ['books.book_id'], ),
    sa.ForeignKeyConstraint(['user_history'], ['users.usermail'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.drop_table('user_history')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_table('user_history',
    sa.Column('logon_id', sa.INTEGER(), nullable=False),
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('book_title', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(length=60), autoincrement=False, nullable=True),
    sa.Column('usermail', sa.VARCHAR(length=60), autoincrement=False, nullable=True),
    sa.Column('date_borrowed', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('return_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('book_returned', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('logon_id', name='user_history_pkey')
    )
    op.drop_table('book_history')
    # ### end Alembic commands ###
