"""empty message

Revision ID: 8f74a2b4c56b
Revises: 
Create Date: 2018-06-10 19:41:15.603177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f74a2b4c56b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_tokens',
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('token_time_created', sa.DateTime(), nullable=True),
    sa.Column('user_usermail', sa.String(), nullable=True),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('token_id'),
    sa.UniqueConstraint('access_token'),
    sa.UniqueConstraint('user_usermail')
    )
    op.create_table('books',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('book_title', sa.String(length=30), nullable=False),
    sa.Column('book_author', sa.String(length=30), nullable=False),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('is_not_borrowed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('book_id'),
    sa.UniqueConstraint('book_author'),
    sa.UniqueConstraint('book_title')
    )
    op.create_table('issued_tokens',
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('revoke_time', sa.DateTime(), nullable=True),
    sa.Column('jti', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('token_id'),
    sa.UniqueConstraint('jti')
    )
    op.create_table('user_history',
    sa.Column('logon_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('book_title', sa.String(length=30), nullable=True),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('usermail', sa.String(length=60), nullable=True),
    sa.Column('date_borrowed', sa.DateTime(), nullable=True),
    sa.Column('return_date', sa.DateTime(), nullable=True),
    sa.Column('book_returned', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('logon_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=12), nullable=False),
    sa.Column('usermail', sa.String(length=30), nullable=False),
    sa.Column('passwd_hash', sa.String(length=30), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('usermail'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('user_history')
    op.drop_table('issued_tokens')
    op.drop_table('books')
    op.drop_table('active_tokens')
    # ### end Alembic commands ###
